
[package]
name = "webtools"
version = "0.1.0"
edition = "2024"


[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"


[[bin]]
name = "check_cbar_inclusive"
path = "check_cbar_inclusive.rs"
